apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-user
  name: mongodb-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-user
    spec:
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-user-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 1000m
            limits:
              cpu: 1000m
              memory: '3000Mi'
          volumeMounts:
            - mountPath: /data/db
              name: user
      hostname: user-db
      restartPolicy: Always
      volumes:
        - name: user
          persistentVolumeClaim:
            claimName: user-pvc
status: {}